更改 geng1gai3 change
操作系统 cao1zuo4 xi4tong1 operating system
笔记本电脑 bi3ji4ben3 dian4nao (notebook computer)

** Sentences
我今年的夏天的时候再一次更电脑的改操作系统
但是我的中文键盘不工作而且我不知道为什么
一些个星期以后我的电脑还是不可能用汉语
自从我还希望用也学习汉语所以我用工作的笔记本


*** Monday
运动 yun4dong4 exercise
健身房jian4shen1fang2 gym
既然 ji4ran2 since
发生 fa1sheng1 happens/takes place
层楼 ceng2lou2 floor
医院 yi1yuan4 hospital
强迫
八个小时长 ba1 ge xiao2shi2 chang2 8 hrs longs
长 chang2 long
强迫 qian1po4 force
加班 jiaban overtime

自从我的太太开始新的工作我和她不可能一起去运动在健身房
既然她最新的工作发生在心脏手术的层楼在jubilee的医院。
她普通工作的月开始的时候。
第一个星期她开始工作早上七点半，第二个星期她开始早上八点，第三个早上十点，第四个中午
她的工作天是八个小时长但是她有时强迫须加班

*** Tuesday
别人 bie2ren2 other people
办公室 ban4gong1shi4 office/bureau
厨房chu2fang2 kitchen
冰箱 bing1xiang1 fridge
苏打 su1da3 soda
责任 ze2ren4 responsability
薄的 bao2de thin
误差 wu4cha1 error
范围 fan4wei2 scope

我的同事和老板喜欢喝酒，所以每一次我去在办公室我们喝酒工作的时候以后
温哥华的办公室看起来好，那里有两个冰箱。 第一个是员工的中午吃饭第一个有啤酒，红酒 而且苏打
新的工作是不错的但是我还是有重要的责任所以我有薄的误差范围

*** Wednesday
木匠 mu4jiang4 carpenter
桌子 zhuo1zi table/desk
装修 zhuang1xiu1 renovation 
承包商 cehng2bao1shang1 contractor
生出 sheng1chu1
森林 sen1lin2 forest
木头 mu4tou wood
头 tou2 head/tete

房子第一层楼的装修做完了
我们花到差不多五万加钱只有装修一个层楼
我们停顿了我们的装修应为承包商的太太会生出在九月
我们希望做完这个夏天。这么办呢


几个年以前我最喜欢的辣椒酱改变了食谱。
我的最好喜欢的辣椒酱叫“是啦差” 由制成金鸡牌。
可是这公司不用一样的辣椒从几个年以后所以他的最有名的辣椒酱品尝不一样。
自从那个时候我尝试一些样的辣椒酱。
于白人的食物我用墨西哥的辣椒酱叫Valentine。这酱很好吃喝便宜。
我找到新的是啦差酱由制成鹅公司。这个酱比甜一点但是我喜欢。
最不一样的辣椒酱是（六福）公司。这个酱吃起来一样韩国的辣椒醬 （gochujang）


--- 31-10-2023 ---
pattern
他做我的旁边 ta zuo4le wode (pangbian) he sat next to me
你做了的选择快的 ni zuo le de xuan3ze2
选择 xuan3ze2 choice
瓶子 ping2zi4 bottle
游轮 you2lun2 cruise ship
失去 shi1qu4 lose (v)
免费 mian3fei4 free (adj)
房间 fang2jian1 room (n)
老人院 lao3ren2 yuan4 old folks home
保险 bao3xian3 insurance (n)
表现 biao3xian4 performance (n)

过辣 guo4la4 too spicy
麻木ma2mu4 numbness (n) numb (adj)
四川 si4chuan1 sichuan province (n)
这个四川的辣椒酱做我的口麻木了  This Sichuan chili sauce makes my mouth numb
花椒 hua1jiao1 sichuan pepppercorn
罐子 guan4zi jar
品质 pin3zhi2 quality
报纸 bao4zhi3 newspaper
改变 gai3bian4 change (v)
过得好吗 guo4 de2 hao3ma is it going well>?
放且 fangqie2 let go
加班 jia1ban1 overtime
食谱 shi2pu3 recipes

起床   qichuang3 wake up
龙舟 long2zhou1 drabonboat
龙舟队比赛 long2zhou1 dui4 bi3sai4 dragon boat team races/competition
巧克力 qiao3ke4li4 chocolate (n)
香草 xiang1cao3 vanilla
蛋糕 dan4gao1 cake
地一个对话 di1yi1ge dui4hua4 first conversation

TODO: colors, 12 animals of the chinese calendar, fruits, veggies

万圣节 wan4sheng4jie2 halloween
邻居 lin2ju1 neighboor
上个万圣节只最近的邻居的孩子进来
糖果 tang2guo3
可是今年的节三个孩子进来和问给糖果
南瓜 nan2gua1 pumpkin
放置 fang4zhi4 place
今年的节我打印了一个小南瓜然后放置在我的门前
前 qian front (n)
包裹 bao1guo3 package
我们在Costco的杂货店买了两个糖果包裹所以我们还有太多的糖果
组装zuzhuang31 assemble (v)
帮助 bang1zhu4 help/assistance  (n)
论坛 xian lun4tan2 forum
在组装我的打印机做的时候我问帮助在一个上网论坛
以色列人 yi1selie4 ren
别人不帮助我可是一个以色列人有了我
我会邮件他一瓶白酒和万圣节的糖果为帮助我

龙舟 long2zhou1 dargon boat
比赛 bi3sai4 contest
团队 tuan2dui4 team (n)\
第一次对话 di4 yi1 ci4 dui4hua4 first conversation
快别人 kuai4 bie2ren2 faster than other
坏 huai4 bad
糟糕的 zaogaode bad
结婚 jie2hun1 marry (v)
婚礼 hun1li3 wedding (n)
婚姻 hunyin1 marriage (n)
请了一天们 qing3le yi1tian1men invite them for a day
考试 kao3shi4 take an exam
别自大 bie2 ZI4da4 do not be arrogant
強迫 qian3po4 forced (v) to do smthg

殖民地 zhi2min2di4 colony
军队 jun1dui4 army 
历史 li4shi3 history
故事 gu4shi4 story
保护 bao3hu4 protect/protexction (n/v)

办公室 ban4gong1shi4 office
笔记本电脑 bi3ji4ben3 dian4nao3 laptop
句子 ju4zi sentences
音调 yin1diao4 tones




我对Linux的品问 my taste in linux ... better than 我的Linux的品问 my linux taste

固定的 gu4dingde
中文键盘 zhong1wen2 jian4pan2 chinese keyboard (n)
输入法 shuru4 enter/import (n/v) fa3 law 
一半年以后左右我固定的电脑中文键盘输入法。
今天以前我用工作的笔记本电脑写我的句子。
品味 pin3 wen tast
味道 wedao taste/flavor
电脑鼠标 dian4nao3 shu3biao1 computer mouse
我对Linux的品问很奇怪因为我不喜欢用一台电脑鼠标
导航用 dao3hang2 yong4 navigate with...
仅使 jin3 (only) shi3 (use) v 
如果你不知道怎么仅使导航用电脑键盘你不可能用我的电脑
自从我的太太有时候用我的工作笔记本电。这台机有容易用的Linux
未来 wei4lai2 future
当然我们未来的孩子会用容易用的Linux的电脑

november
有风 you3feng1 windy

上个星期五的天气开始不错的但是有风的可是中午的时候以后

薄雾 bo2wu4 mist/fog
更近 geng4jin4 closer

那个工作的天没什么特别的但是我可以看着薄雾越来越更近
收到 shou1 dao4 accept
接受 jie1 shou4 receive
信息 xinxi message
渡船 du4chuan2 ferry
当下午我受到一个新闻从我的太太为渡船
取消 wu3xiao1 cancelled
读 du2 read 
新闻读起来像这样每一个渡船晚上6点以后取消
应该 ying1gai1 should
我读到这个新闻大概下午3点半左右然后我对老板说“我应该离开现在”
匆忙的 cong1mang2de be in a hurry
手机 shou3ji telephone
桌子 zhuozi table
自从我匆忙的我忘记了哪里我上办公室桌子我的手机

公共汽车gong1gong4 qi4che1 bus
旅行lv3xing2 trip
压力 ya1li4 pressure
情况 qing2kuang4 situation
旅程 lv3cheng2 journey
公共汽车的旅行有压力的因为很多人的情况一样我的
更长 gengzhang3 longer
渡船的旅程是百分之百五十更长了
pattern: 新闻读起来像这样


# to sort

紧张 jin3zhang1 nervous
古代 gudai3dai4 ancient
控制 kongzhi4 control 
记不住 ji4bu4zhu4 can't remember
名次 ming2ci4 
绝对是 juedui4shi absolutely
学问 xue2wen4 knowledge
教授 jiao4shou4 professor

狗屁 gou3pi4 bullshit/nonsense
好像是你的衣服不好看
好像是 hao3xiang4shi4 
什么都没有钱 shen2me dou1 mei2you3 qian2 nno money for anything
心理学 xinli xue2 psychology (heart inside study)

不到一年 bu4 dao4 yi1 nian2 in less than a year
加入 jia1ru4 join
团队 tuan2dui4 team
不到一月的时候以前我开始工作最新的团队 


发送 fa1song4 send (v)*
我的工作把我失发的手机发送我
帐户zhang4hu4 accounts
访问 fang3wen4 access 
所以我现在可以访问工作的帐户们
电子 dianzi electricity
我的打印机有一个问题它不可能打印因为我有电子问题
信号 xin4hao4 signal
测量探头 ce4liang2 tan4tou2 measuring probe 
这个打印机的测量探头发送不好的信号
以色列 yiselie4 isreali
我应该告诉我的以色列的盆友关于我的问题
有一句话如果你只有一打印机有零台打印机
维修 wei2xiu1 repair
坏掉的打印机 huaidiao4 broken
因为打印机通常有问题所以你用第二台打印机维修第一台坏掉的打印机


Snowrunner
视频 shi4pin2 video
游戏 you2xi4 game

当最近的Steam销售开始我买一个电脑游戏叫 “snow runner“
卡车 ka3 che truck
穿过 chuānguò through (v)
泥泞 ni2ning4 mud
雪地 xue3di4 snow
在这个游戏你驾驶最大的卡车穿过泥泞和雪地
级 ji2 level
当然你开始这个游戏一级而且最好卡车的东西还不能用
项目 xiangmu3 project
任务 renwu4 task
早期 zao3qi2 early
晚期 wanwi2 later

高速公路 gao1su4 gonglu4 highway
公路轮胎 gong1lu4 lun2tai1 highway tires

例如早期一任务问你驾驶从这里到到那里用公路轮胎
可是每一个路沾满泥泞的所以我常常陷在泥里


放松 fang4song1 relaxing
安全 an1quan2 safe
有人找这样游戏无聊可是我喜欢
不宽容的 kuan1rong2de
恼人 nao3ren2 annoying
游戏的地图是非常不宽容的所以早期那个游戏很难和恼人的