*
** /09/2023
材料cai2liao4 mATERIAL
带进来dai4 jin4lai2 bring in
带进出bring dai4jin4chu1 in and out
带出去dai4 chu1qu4 take out
森林大火senlin2 da4huo1 forest fire
森林 senklin forest

换提huan4ti exchange
房租fang2zu rent
房租 chu1zu1 rent
出租车chu1zu1 che1 taxi
国际学生guo4ji4 xue2sheng1 international student
国际 guo4ji4 international
世界 shi4jie4 world

打算da3suan4 plan
计划ji4hua4 plan
旅馆 lv3guan3 hotel
服务fu2wu1 serve
变成 bian4cheng2 become
放轻松 fang4qing1song1 take it easy
放轻松的颜色 ... de yanse relaxing xcolor
油漆 youqi paint
完成 wan2cheng2 finish
四个月的时间 si4ge4yue4de shijian four months
拆掉了chai1 diao4le demolished
死掉了si3 diao4le died
烧掉了shao1 diao4le burned
房子和公寓被烧掉了houses and partments burned down
烧烤 shao1kao3 bbq

年底 nian2di3 end of year
年中 nian2zhong1 middle of the year
年初 nian2chu1 start the year

上旬 shang4xun2 first to days of the month
中旬 zhong1xun2 middle 10 days of the month
下旬 xia4xun2 last 10 days of the month

** 

教堂 jiao4tang2 church
教师 jiao4shi teacher
房价 fang2jia4 house price
幸运 xingyun
休假 xiu1jia take a vacation
学习 xue2xi2 study
休息 xiu1xi rest
睡觉 shui4jiao4 sleep
海边hai1bian1 (beach) seaside
小憩 xiao3qi4 take a nap
加班 jia1ban1 overtime
轮流来 lun2liu2lai2 take turns
门铃 men2ling4 doorbell

日出 ri4chu1 sunrise
日落ri4luo4 sunset
需要xu1yao4 need
吓一跳xia4yitiao4 startled

他很讲究他的衣服 he's very peculiar wrt clothes
鞋子xie4zi shoes
鞋子 ku4zi2 pants
review colors, streets/city, directions(cardinal + close/far), clothes

24/09/23

特殊 te4shu1 special
特别 te4bie2 special (especially)
除了 chu2le apert from
我得喝两杯咖啡  I HAVE to derink 2 cups of coffee
我得开车很快的 I HAVE to drive fast
得 dei must 
首先 = 第一 first
去名字 qu ming
有出席 you3 chu1xi2 attended
他对衣服特别讲究 he's particular about clothes
讲究 jiang3jiu4 particular/peculiar
dai (wear accessories)
chuan (wear clothes)
博士 bo2shi4 phd
研究所 graduate school
足够的 zu4gou4de enough
高中 gao zhong1 high school
(面)包 mian4bao1 loaf of bread
(一双)鞋子 yi shuang xie2zi a pair of shoes
一(张)纸 yi (zhang) zhi a piece of paper
一(台)电视 yi tai dianshi a tv
一(条)狗 ti tiao2 gou3 a dog
一(辆)车 yi liang4 che1 a car

对话dui4hua4 dioalogue
仍然 reng2ran still
还是 haishi still
完成 wan2cheng2 finish
# 办公室 ban gong shi office
教堂 jiao4tang2 church
习惯 xi2guan4 habit/used to)
任务 ren4wu task
只是 zhishi only
只有 zhioyou only
旅馆 lv3guan3 hgotel
进步jin4bu4 progress
业为yewei4 industry

** Sentences
孙子珺 sunzi jun
澳大利亚 ao4da4liya australia
心脏医生 xin1zang2 yisheng1 cardiologist
一个太太的同事是一位医生从澳大利亚
祖国 zu3guo2 home country
完成wancheng complete
研究所 yan2jiusuo3 gard school
他完成研究所心脏医生在他的祖国
仍然 rengran
仍然他不可能工作在他的祖国的医院
获得 huo4de2 get
经验 jing1yan4 experience
需要 xuyao needs
如果他要到获得经验他需要离开澳大利亚
赚钱 zhuan4qian2 earning
所以他住在维多利亚获得经验赚钱大概七万元作为一名心脏医生
赚钱
关于 guanyu about
他为心脏医生工作在维多利亚。这位医生赚钱关于一百万。
反正我们买了他的电视以前他最近回奥地利呀的时候

工作给我一台笔记本电脑所以我和太太一起连接到电视。
台笔记本电脑 (tai) bi3ji4ben dian4nao3 laptop
连接到 laing2jie1dao connected to
除非我得上班在办公室我从来没有用这台笔记本电脑。
除非 chu2 fei unless
所以在我的家我和太太一起用那台机看电影。
我和太太的结婚周年是今天
结婚周年 jie2hun (marry/get married) zhounian2 anniversarry
所以我请了一天工作假。我们今天在越南面店fort路吃到越南面。
越南面店 yue4nan2 mian4 dian4 vietnamese noodle shop 