:PROPERTIES:
:ID:       bea8a389-c934-4d5d-8478-6721780a4f95
:END:
#+title: How I would fix DND

* How I would fix the DND

While never given great rank, responsibilities nor consideration for such, I did spend a total of 13 years in the Canadian Navy, including my formatives years at the Royal Military College of Canada, where I served with great and awful leaders alike. The opinions and experience in this text are mine alone and touch issues that mostly plagues the Canadian Navy, while also applying to the other branches.

It is apparent that this important instituton has fallen into a state of disrepair for many reasons such as: lack of personel, antiquated materiel, cost of living and pay, disastrous IT, inability from leaders to grasp the lessons of the past and the future, cost on family life, and toxic bureaucracy and red tape chief amongst them.
Of course this isn't an exhaustive list as I hope to propose solutions based on my experience during and after my time in the military.

We cannot demand our officiers and personnel to display pride when they do not themselves deeply feel a sense of pride in the work they do and that it actually matter.
How can we expect them, to give the ultimate sacrifice if they, do not wholy trust in themselves, their leader and this organization

** Recruitment/lack of personnel

Time serving our nation cannot solely be a time of self-sacrifice to one's family, health both physical and mental and finances. Civilians joins this instution for a multitude of reasons: from escaping poverty, a desire for change or a deep sense of duty to one's count.
Whatever reasons drove one's to make its way to the recruitment center, their application should be processed within 2 weeks, with their medical done within a month. While its fine for someone finishing school to wait a year for an answer whether or not the military will accept him is fine, it is unacceptable for anyone that in the spur of the moment to submit an application and never hear back.
Recruitment center processing method has to be revitalized. Whether we decide to process one's application by hand like its the 1950s or some other methods we have to act now, and take a decision.

** Antiquated materiel

All branches of the Canadian military sports some kind of equipment that would make museum jealous. Be the Canadian Navy proud tradition of raiding naval musuems for spare parts for the steam powered protector class, or the Canadian Air Force doing the same for the sea king so that "yesterday's aircraft may fly tomorrow". This is the result of

** Toxic bureaucracy, distributed decision making, and

Enacting change in the military, big or small, is nigh impossible. The process of changing something requires some sort of permission from above who themselves recursively require permission from above and so on and do forth. All that is required, is one superior feeling risk averse to deny all the efforts placed forth to bring a positive change.
Decision making in the Navy, is a distributed mess. While captains and admirals sees themelves the very same way as the English captain portrayed in "Master and Commander: The Far Side of the World" the reality couldn't be futher from the truth. Decisions are often taken in agreement of each party, and when failure comes it becomes very hard to find the root cause of what led to these decisions

** Large project procurement

The canadian ship building act, is a scam. If the goal was to provide actual value to taxpayers, canadians, and our armed forces we would bulk order ships from the states, europe, or Korea. We wouldn't be paying a billion dollar per hull, and they would actually be delivered on time and on budget.

** Cost of living

** Internal responses

floods, fires, and climate change. Jasper burned, which city is next? Floods will become. Create a unit where they can have actually a good deal. Anyone can join

** incompetence
We promote people until they are incompetent and for officers even beyond that point, then they stay where they are until they retire.

We must rethink how NCOs are paid, some stellar and incredibly talented sailor and corporals have no desire to move on and become sargents and above as they not only love their craft but also excels at it. We must allow for a salary compensation that

A stellar example comes from HMCS corner brook running aground in 2011 where the ship's captain single handely forgot that in the event where one doesn't exactly know his position including the delta positional error over time underwater that unknown technologies like sonar can be used to adequately measure one proximity to the sea floor while in home waters.
Another stellar example arised in 2017 when the Chief of the Navy had the brilliant idea of combining all marine engineering (stockers, electricians and hull technicians) into a single entity. Even after countless feedback that such decision was terrible, we charged ahead with these changes and can directly attribute the current Navy's disastrous personnel sortage on that decision.

** Pervasive culture of "no-failure"

There is this pervasive culture of labelling small and big tasks, with or without merit, as no fail missions. This tend to

** Realities of modern day conflicts

Ukraine not only survived Russia's land, air, and sea onslaught, but also humiliated the aggressor through quick adaptation, a brutal iterati6ve process akin to modern day tech start-up, and a can do attitude.
We cannot look down upon them, from our NATO pedestals, as merely an ex soviet military organization, but as the forefront innovators of what the next war will bring about.


We have slept a long and terrible slumber, we have left Afghanistan as broken as the day we first came with our green uniforms, our sailors are gone and our ships are relic from the past

regardless of one's political affiliation we cannot
