:PROPERTIES:
:ID:       6d4dddae-e062-4be1-a06c-251d7232b1cc
:END:
#+title: Chinese sentences

* Related
[[id:a36e062b-16a6-4b54-9a05-4f97fff5d744][Chinese words group]]
[[id:d2b75711-ccdf-46f8-b645-f82a43bf2a36][Chinese basic patterns]]
[[id:57f6f7f9-dd12-4d99-b2dc-aeeb43908340][Chinese often forgotten words]]
[[id:0f85085c-38b5-474b-984b-b3f6c94e6404][Chinese class notes]]

* Q1 2024
** 03 日 01 月 2024 年
1. 这个圣诞节的时候我发现日本相扑
2. 我以前觉得相扑可起来很容易的运动如果你是最大的运动员你会赢
3. 可是越学习越明白多为什么我错了
4. 当然有相扑运动员有 220 公斤多可是有时候他体重 120 公斤
5. 在 2016 的时候当加拿大海军日本旅行我吃在一个相扑餐厅
6. 在这次我自己独自所以我座由烹饪区旁边厨师
7. 我觉得他是了一位相扑员在年轻的时候 wo zuo zai chushi de pangbian
8. 他不说英文和我不能说日本文但是我们可以用运动和锻炼语言明白一起
9. 在这家餐厅我吃相扑汤叫 ChanKoNaBe
10. 吃饭以后餐厅的厨师给我一张相扑排行榜叫 Banzuke。我感觉了很感动
11. 相扑的生活方式提醒我海军的时候因为你只有一个目标成为最大的人最强人
12. 我觉得相扑员必须一边号运动员一边好厨师

** 16 日 01 月 2024 年
1. 这个星期一我们开始第一个层楼的装修
2. 现在我和太太一起向大学生一样生活因为我们没有一间厨房
3. 我们不可能做特别复杂的菜然后我们只可能用洗手间水槽清洗碗碟
4. 我们感觉很幸运我们可在两个装修之间存了钱
5. 我们在装修的时候以前已经尽力做好准备
6. 我们冻了很多的剩菜所以我们会必须洗碗很少的碟
7. 装修有压力的所以我会带我的太太更经常地外出吃饭
8. 我感觉工作特别难因为噪音太大所以我穿耳朵保护

** 24 日 01 月 2024 年
1. 上个周末我开始打印机的重建
2. 这个活动我从一些月以前计划了
3. 上次我建造这个的打印机我感觉很泄气因为我需要请求帮忙
4. 当比利时的旅行为两个礼拜我付钱一个人退休了还军人维修这部打印机
5. 他维修很多的问题我的打印机但是他电子的做糟糕的
6. 几个星期之后我开始我的打印机但是不明白怎么做打印机的软件。所以我是很高兴以色列的朋友帮助我
7. 从那之后我知道有一天需要重建这部打印机
8. 这次我学会了怎么做打印机的电子

** 31 日 01 月 2024 年
1. 我的太太不仅喜欢中国古代的电视节目而且他每一个年看一看两部她的最喜欢的节目
2. 她两部最喜欢电视节目是叫琅琊榜(lang2ya2bang3)和后宫甄嬛传 (hou4gong1 zhen1huan2 chuan2)
3. 她看得很多次这两部节目所以她几乎能背诵了(bei4song4le)故事 
4. 有时候我一边做一个东西我一边停止我的做和看一下她的电视节目
5. 我早上又开始了骑自行车因为我怀念就军的上下班时光
6. 还有，如果我不运动至少每一个星期四次我变胖

** (next month)
1. 你看不看电视节目叫《繁花》它释放了上年.

** 07 日 02 月 2024 年
na men
爱好 ai4hao4 hobby - note the 4th tone on 好
之前 zhi1qian2 previously
成为 cheng2wei2 become
打印 da3yin4 printing (v)
在打印机成为我的爱好以前，我从来没有买一个东西从 Aliexpress
零件 ling2jian4 parts 
在开始的时候我买打印机的零件从 Amazon 的网上店
网上卖家 wang3shang4mai4jia1 online seller
网上买家 wang3shang4mai3jia1 onlien buyer
转售 zhuan3shou4 resell
有什么不对...他 you3shen2me bu4dui4 something's wrong ... with him
当然 Amazon 网上店越来越坏的也是我听说很多网上卖家转售中国事儿 
有网卖家百分之两百多 there are more than 200% of online sellers
有些加拿大网上卖家比 Aliexpress 的价格贵双倍
照片 zhao4pian photos
产品 chan3pin3 product
有也是加拿大卖家用一样的中国卖家产品照片
但是百分之八十 Aliexpress 的卖家没有运送费也是他们从中国发货
发货 fahuo ship
我也是可以买比较好打印机的零件从那里
我觉得下个打印机我会买从中国的网上店
无法 wu2fa3 unable (adj)
参加 can1jia1 participate (v)

刚(gang)解决一个问题那么(name)找到新的
解决 jie3jue2 solve
修了 xiu1le fix


** 14 日 02 月 2024 年

经济 jing1ji4 economy (adj/noun)
经历 jing1li4 experience/skill (n) experience/undergo (v)
情况 qing2kuang4 situation
技术部门 ji4shu4bu4men2 technology sector
加拿大经济的情况看起来坏的特别为技术部门
招聘 zhao1pin4 advertise job offers
启事 qi3shi4 notice
在上个工作的结束(jieshu)和现在之间我看很少电脑工程师的招聘启事
成立 cheng2li4 establish (v)
比如上一次我找工作我看至少二百招聘启事(zhao1pin4qi3shi4)在维多利亚当地的商业
当地 dang1di4 local
商业 shang1ye4 webpage
这一次我只发现差不多二十六工作的招聘启事
上个礼拜我的工作开除百分之二十的工人
高级电脑工程师 gao1ji2 advanced/high level
我的部门丢失(diushi)三位高级电脑工程师
很多的同事感觉难过(nanguo)对最近的开出因为他们被喜欢
失去 shiqu4 lose
所以我担心关于我的情况因为我不买得起失去我的工作

*** preparations
专修 zhuan1xiu1 specialize

更近 geng4jin4 closer
装修(zhuangxiu)有一天将结束 (jianjieshu)

Tp go beyond
这个单词用哪一个语气
好久不见,
你记得那时我告诉你关于我与太太一起看着中国电视节目
如果我一天我可能明白中国人我应该看看越来越多中国节目和视频(shipin)
重新发现 chong2xin1 fa1xian4 rediscovered
我最近重新发现 MandarinCorner 的视频在 YouTube
两个年以前左右我试试看看 Mandarin corner 的视频但是我这可以明白百分之二十
我喜欢这个 YouTube 频道就是她讨论挺有趣

** 27 日 02 月 2024 年
装修完成的时候我们会有少钱
但是现在到三十年以后我们希望付很少钱为房子新的东西
虽然装修完成之后我们会试试看存钱
上个星期最近安装地板但是房子还有小工作之前我可能住在
地板 di4ban3 floors
地板脚线 di4ban3jiao3xian4 floor mouldings
层油漆 ceng2you2qi1 (m.w.) coat of paint
我们还没有完成地板脚线也是没有开始第二层油漆
** 28 日 02 月 2024 年

** 07 日 03 月 2024 年
另一个 ling4yige4 another one
推荐 tuijian4 recommend (v)/recommendation (n)
受到 shòudào receive/get
我有另一个太太的推荐中国电视节目。
叛逆者 pan4ni4 zhe3
这个电视节目叫叛逆者叫《叛逆者》被做了 2021
主角 -hu3jiao3 main character
进化 jinhua evolution
有意思的故事和主角的进化是很好
国民党 guo2 ming2 dang3 kuomitang
共产 gong4chan3 communist
内战 nei4zhan4 civil war
这节目的故事关于在国民党和共产的内战
间谍 jian4die2 spy
每一个重要人物是间谍
结束 jie2shu4 end
背叛 beipan betrayals
每一个重要人物是间谍所以你有很多的背叛从故事开始到结束
占领 zhan4ling3 occupy
故事的中间有中国各日本战开始和他们占领上海的城市
宣传 xuan1chuan2 propaganda
虽然这个电视节目的故事很好的我觉得中国共产用这个节目为毛泽东作宣传
耶稣 ye1su1 jesus
来到 lai2dao4 come
时刻 shike moment
因为主角有一个来到耶稣时刻在那时候主角和一个朋友一次讨论关于毛泽东的想法。
然后为什么这个想法最好为普通的中国人
普通 pu3tong1 ordinary


** 13 日 03 月 2024 年

我与太太上个周末一起吃饭在《小雨喃》餐厅因为我们都想喝热汤
服务员 fu2wu4yuan2 waiter/server
进入着餐厅我认识服务员然后说《好久不见》
点 dian3 order
海带 hai3dai seaweed
我们坐了在一个桌子和点两碗传统汤，一盘泡菜和一盘海带
通常这家餐厅的泡菜非常辣但是这次问道不特别辣
鲜 xian1
我想到我可以吃越來越辣的菜但是服务员给我最新鲜泡菜
哭泣 ku1qi cry
这家餐厅最老的泡菜可以让我哭泣

** 20 日 03 月 2024 年

有一次在二月的时候我上班办公室差不多我错过了温哥华对维多利亚的船
放长假 fang4chang2jia4 long weekend
这是放长假之前周五我想到旅行顺利的
当然我错的
公共车 gong1gong4che1 bus
地铁 di4tie2 subway
车站 che1zhan4 station
从温哥华的办公室到公共车车站于地铁有问题
那个二月的天地铁服务的问题所以又只有很少的地铁火车
那天我的运气很多因为地铁火车看起来日本高峰时间所以我空间不大
地铁车厢 di4tie1 che1xiang1 subway car wagon
例如地铁停在下个的车站但是地铁车厢不可能人进门
好不了多少 hao3 bu4liao3 duo1shao3
预定 yu4ding4 scheduled?
到达 dao4da2 arrive
公共车车站好不了多少因为公共车预定到达下午五点三刻
当然公共车不到达所以我一边等二三十分钟多一边我觉得从来没有可以回家
公车司机 gongche1 si1ji1 bus driver
公共车最后到达然后公车司机说别付钱只进来
车祸 che1huo4 accident
公车司机迟到了因为有车祸旁边公共车车站
渡船 du4chuan2 ferry
我只坐渡船温哥华到维多利亚因为渡船也是迟到了
