:PROPERTIES:
:ID:       0f85085c-38b5-474b-984b-b3f6c94e6404
:END:
#+title: Chinese class notes

* Related

[[id:a36e062b-16a6-4b54-9a05-4f97fff5d744][Chinese words group]]
[[id:d2b75711-ccdf-46f8-b645-f82a43bf2a36][Chinese basic patterns]]
[[id:57f6f7f9-dd12-4d99-b2dc-aeeb43908340][Chinese often forgotten words]]

* Mandarin corner notes

有趣 you3qu4 interresting
有意思 you3yi4si interresting
社交媒体 she4jiao1 mei2ti3 social media
话题 hua4ti2 topic
YouTube 频道 pin2dao4 channel

* Class notes
** since 24 日 01 月 2024 年
我会有很多像他学习的地方
随便 sui2bian4 at your convenience
随手 sui2shou3 at your convenience
*** TODO review all of the clothes/accessories
都快要三月 its almost march
几乎 ji1hu1 almos
对这间餐厅满意
对...满意 bui4 (what) man3yi4 satisfied
感到 gan3dao4 feel
感觉 gan3jue2 feel
才 cai then
服务 fu2wu4 serve
挺不错 ting3bu4cuo4 (pretty good)
很不错 ...
非常不错 ...

** since 21 日 02 月 2024 年
相信 xiang1xin4 believe
想 xiang3 think
肉店 rou4dian4 butcher shop
中国城 zhong1guo2cheng2 chinatown
城市 cheng2shi4 city
同性恋 tong2xing4lian4 gay
严重大 yaszhong da seriously big
严重 yazhong seriousy
重要 zhong4yao4 important
讨论 tao3lun4 discuss

** since 27 日 02 月 2024 年
** since 11 日 03 月 2024 年
我对麻将有兴趣  I am interrested in mahjong
自读卡片 zi4du2 ka3pain4 sel-reading cards?
收集 shou1ji2 collect
玩得开心 wan2de kai1xin have fun
肚子饿 du4zi e4 hungry
第一选者 di yi xuan3zhe3 first choice
嘈 cao2 noisy
安静 anjing4 quiet
向 xiang towards
扑克牌 pu1ke4pai2 poker
比赛 bi3sai4 game/match
赢 ying2 win
先开始 xian1kaishi3 start first
规定 guiding rules
数字 shuzi rules
一回事 yi huishi one thing
路上 lu4shang4 on the road
大部分 dabufen most
一部分 yibufen part
理解 li3jie understand = 明白

** since 20 日 03 月 2024 年
名词 ming2ci2 noun
动词 dong4ci2 verb

了解 liao3jie3 learn
熟悉 shu2xi1 familiar
顺利 shun4li4 comfortably
另外 ling4wai4 in addition
性格 xing4ge2 character
内向 nei4xiang4 introvert
改变 gai3bian4 change (verb)
学校 xue2xiao4 school
*** Pattern
游泳游得好 you2yong3 you2 de hao3 swim well
打篮球打得好 da3 lan2qiu2 da3de2 hao3 good at basketball

** since 01 日 05 月 2024 年
没有办法 mei2you3ban4fa3 there is no way

被取代 bei4 qu3dai4 to be replaces
客服 ke4fu customer service
客户 ke4hu4 client
客人 ke4ren2 guest
薪水 xin1shui3 salary
海啸 hai3xiao4 tsunami
*** 变成 bian4cheng2 become
你曾经吗 ni3 ceng2jing1 ma
讯息 xun4xi2 message
度蜜月 du4mi4yue4 honeymoon
蜂蜜 feng1mi4 honey
刚刚 gang1gang1 just
刚才 gang1cai2 just now
我变得越来越胖 I am becoming fatter
你打电话给我的时候 when you call me
我刚回家 I just got home
报税 bao4shui4 tax return
退税 tui4shui4 tax refund
多付 duo1fu4 overpayment
旅馆 lv3guan3 hotel
报 bao4 return
很可怕 hen3 ke3pa4 very scary
口音 kou3yin1 accent
音乐 yin1yue4 music

** 02 日 05 月 2024 年

顺手帮我带... shung4shou3bang1 wo3 dai4... can you bring me ...
不顺口 bu4 shun4kou3 not smooth
不顺利 bu4 shung4li4 not smooth
其实 qi2shi2 actually/in fact
感动 gan3dong4 moved (emotionally)
简单 jian3dan1 / 容易 rong2yi easy/simple
超级市场 chao1ji2 shi4chang3 supermarket
员工结帐 yuan2gong1 jie2zhang4 employee checkout
拿走 na2 zou3 take away
经验 jing1yan4 experience
大麻烦 da4ma2fan big trouble
会员 hui4yuan2 member
变 bian4 change
比赛 bi3sai4 contest/match
社会 she4hui4 society
副业工作 gu4ye4 gong1zuo4 side job
抱怨 bao4yuan4 complaint
柜台 gui4tai2 counter
你应该自己试试看修理 you should try to fix it
修理 xiu1li3 fix
足够的 zu2gou4 de enough
注意 zhu4yi4 notice
*** 主机 zhu3ji1 host
二手 er4shou3 second hand
付会员 fu4hui4yuan2 paid member

** 07 日 05 月 2024 年
害怕 hai4pa4 afraid
可怕 ke3pa4 scary
房间 fangjian room
就算 jiu4suan4 eventhough
即使 ji3shi3 eventhough
找到 zhao3dao4 have found
另外 ling 4wai4 in addition
吵架 chao3jia4 fight verbally
打架 da3jia4 fight physically
参加 can1jia1 join/participate
不仅 bu4jin3 not only
决定 jue2dung4 decide(v) decision(n)

抽烟 chou1yan1 smoking
吸烟 xi1yan1 smoking

** 14 日 05 月 2024 年
**** 相反 xiang1fan3 opposite
**** 相仿 xinag1fang3 similar
交通 jiao1tong1 transportation
在温哥华路的旁边 next to vancouver road
免费 mian3fei4 free
费用 fei4yong4 fees
塞车 sāichē traffic jam
退休 tui4xiu1 retire
塑料 su4liao4 plastic
紧急 jin3ji2 urgent
平均 ping2jun1 average
继续 ji4xu4 continue
高级 gao1ji2 advanced
没有受欢迎 shou4huan1ying2 not popular
没有受聘 shou4pin4 not employed
收高教 receive higher education

** te
正在 zheng4zai jsut at
熊猫 xiong2mao pandas
染 ran3 dye
染头发 ran3 tou2fa3 dye hair
正在工作 zheng4zai gong1zuo4 working (currently working)

** bro

收到 shou1dao4 receive
A 比 B 高百分之八 A is 8% higher than B
对你来说什么有趣
只猫 zhi3mao1 cat
脾气 pi2qi4 temper
骂脏话 ma4 zang1hua4 swearing
骂 ma4 scold
地板脏 di4ban3 zang4 dirty floor
推车被我们放回去 put the cart back
咖啡杯我喝完了 I finished my coffee
我把咖啡喝完了 wo3ba3kafei1he1 wanliao
地方 di4fang place
原来 yuan2lai2 orginal
我把推车方去原来的地方 pushed the cart back to its original place
全部 quan2bu4 all
节目 jie2mu4 tv program
价钱合理 jia4qian2 he2li3 reasonable price
越来越糟糕 worse and worse
糟糕 zao1gao bad
出租 chu1zu1 rent
活动 huo2dong4 activity
结束 jie2shu4 finish
借书 jie4shu1 borrow book
还书 huanshu1 return book

** test

当我开车的时候
当 ... 的时候 pattern
快乐 kuai4le4 happy
幸福 xing4fu2 happy
想办法
喝办法
...办法 pattern ? e.g. 喝办法
退休金 tui4xiu1 jin1 pension
金 jin1 gold
退休 tui4xiu1 retirement
退休人 tui4xiu1ren retiree
股票 gu3piao4 stock
改变 gaibian change
赔钱 pei2qian2 lose money
抓钱 zhua1qian2 make money
大便 da4bian4 poop
*** 最好不要丢你的工作 better not lose your job
丢 diu1 lose
对修 dui4xiu1 repair
最好不要丢你的妻子 ...wife
存款 cun2kuan3 deposit
存款钱 deposit money
1 百万 yi bai3wan4 1 million
员工 yuan2gong1 staff/worker
最带原 zui
最好特别原来的  best especially the original one
原来 yuna2lai2 original
日历 ri4li4 daily calendar
月历 yueli4 monthly calendar


** since 10 日 09 月 2024 年
装修 zhuang1xiu1: renovations
我唱歌的能力是坏的 my singing ability is bad
坏 huai4: bad
修车 xiu1che: car repair
起初 qi3chu1: at first/originally
床铺 chuang2pu4: bed
睡觉上我的床铺 sleeping on my bed
其实 qi2shi2: actually
应征 ying4zheng: interview process
员工 yuangong: employees
工人 gong1ren1: labourers
真空 zhen1kong: vacuum (act of vacuuming ) or like a power vacuum
把真空你的间卧房 vacuum you bedroom
学期 xue2qi2: semester
改变 gai3bian4: change
团体 tuanti: group
多大你的团体 how big is your group
活动 huo2dong4: activity
哪一个编码的方面你不喜欢 what aspect of coding do yo not like?
*** 慢 man slow
*** 低 di1 low
级 ji2 class
程度 chengdu: level
卡车 ka2che1: truck
右边 youbian: right
左边 左边：left
*** 方便 fangbian: convenient
很酷 hen3ku4: very cool
呕吐 ou1tu4: vomit
无聊 wu2liao2: bored/boring
*** 厨房 chu2fang2 kitchen
乱七八糟 luan4qi1ba1zao1: (expression) messy
动物 dong4wu4: animal
宠物 chong3wu4: pet

** 18 日 09 月 2024 年
闻的 wen2: smell
味道 wei4dao4: taste
问道鸡肉的味道 asked about the chicken
嘈 cao2: noisy
基层 ji1ceng2: basic level
超速 chao1su4: speeding
速 su4: speed
高速 high speed
故意 gu4yi4: on purpose
聊天 liao2tian1: chat
通知 tong1zhi1: notify
陌生人 mo4shen1 ren2: stranger
外国人 wai4guo1 ren2: foreigner
本来 ben3lai2: originally
文件 wen2jian4: document
交出文件 jiao1chu1 wen2jian4: hand over documents
*** 要求 yao1qiu2: require
每一天我要求我的太太做早饭 Everyday, I require my wife to make breakfast
副词 fu4ci2: adverb
连词 lian2ci2: conjunction
名词 ming2ci2: noun
动词 dong4ci2: verb
*** 马上 ma3shang4: immediately
户头 hu4tou2: account
北京的口音 beijing accent
口音 kou3yin1: accent
键盘 jian4pan2: keyboard
资料 zi1liao4: data
空间 kong4jian1
电脑硬盘没有空间 no space left on the computer's drive
硬盘 ying4pan2: harddrive
数据库 shu4ju4ku4: database
哪一个云对有我们的数据库 which cloud has our database
工程师 dong1cheng2shi1: engineer
费用 fei4yong4: fees
存钱 cun2qian2: save money
花钱 hua1qian2: spend money
*** 辛苦 xin1ku3: hardworking
*** 租金 zu1jin: rent
办公室 ban4gogn1shi4: office
加币 jia1bi4: CAD $
无人机 wu2ren2ji1: drones
戏剧 xi4ju4: drama
你的生活有多的戏剧吗 how much drama is there in yoru life?
*** 设计 she4ji4: design
*** 维修 wei2xiu1: repair
汲取 ji2qu3: draw
生产 sheng1chan3: production

** 25 日 09 月 2024 年
选举 xuan3ju3: elections
赢了 ying2le: won
强大 qiang2da4: strong/powerful
我越听你我变得越来越笨 the more I listen to you the dumber I become
*** 相信 xiang1xin1: believe
*** 突然 tu2ran2 suddenly
虽然 sui1ran2: although
本来 ben3lai2: originally
脚断掉了 the foot is broken
断掉 duan4diao4: broke
借这个机会 take this opportunity
借 jie4: borrow
是什么事情 what is it?
一岁六月大 a year and half old

请病假 qing3bing4jia4 calling in sick
休假 xiu1jia4: take a vacation

兴趣 xing4qu4: interest
有趣 you3qu4: interesting
有意思 you3yi4si: interesting

福利 fu2li4: welfare
乱七八糟 luan4qi1ba1zao: messy
走走看看 zou3zou3kan4kan4 go see
边走边吃 bian1zou3bian chi: eat on the go
狗屁 gou3pi4: (swear word)
规定 gui1ding4: regulation
租金 zu1jin1: rent
邻里 lin2li3: nei8ghborhood
邻居 lin2ju1: neighbor
开会 kai1hui4: meeting
派对 pai4dui4: party (brithday/or else)
黄色 huang2se4: yellow
黄色的校车 yellow school bus
公共汽车 gonggongqiche: bus

主人 zhu3ren2: owner
住 zhu4: live
马路的旁边 ma3lu4 ... beside the road
马路 ma3lu4: road

认真的人: a serious person
我会付更多税 I will pay more taxes
税 shui4: taxes
**** 努力 nu3li4: effort
**** 相信 xiang1xin4: believe
失去 shi1qu4: lose
越说越好 the more I talk the better

总统 zong3tong3: president
总理 zong3li3: premier/prime minister

** 9 日 10 月 2024 年
招聘人员 zhao1pin4 ren2yuan2: recruiter
学习 xue2xi2: study
飓风 ju4feng: hurricane
风 feng1: wind
*** 总共 zong3gong4: total/altogether

总统 zong3tong3: president
总理 zong3li3: premier/prime minister
选举 xuan3ju3: election
选票 xuan3piao4: voting ballot (the one with the candidate names)
赛车 sai4che1: racing?
在车 in the car
蛇 she2: snake
修理鞋子的人 xiu1li3 xie2zi de ren: shoe repairman
修理的人 xiu1li3 de ren: repairman

机会 ji1hui4: opportunity
留 liu2: leave/remain
准备 zhun3bie4: ready/prepared
机会是留给有准备的人 opportunities are reserved for those who are ready
印象 yin4xiang4: impression
留个好印象 : leave a good impression

**** 月初 yue4chu1: beginning of the month
**** 月中 yue4zhong: middle of the month
**** 月底 yue4di3: end of the month

鞋底 xie2di3: sole (of a shoe)
在 Vancouver 和 Cook 马路的路凑 : at the intersection of Vancouver and cook streets
**** 高于 gao1yu4: higher than
**** 少于 shao3yu2: less than
**** 低于 di1yu2: lower than
关于 guan1yu2: about
接受学生 xie1shou4 xue2sheng1: accept students
学教 xue2jiao4: teach
屠夫 tu2fu1: butcher
功夫 gong1fu1: kung fu
历史 li4shi3: history
亚洲 ya4zhou1: asia
欧洲 ou1zhou1: europe
三千年的历史 3 thousand years of history
高级 gao1ji2: advanced
阶级制度 jie1ji2 zhi4du4: class system
不公平 bu4 gogn1ping2: unfair
费用 fei4yong4: cost/fees
买单 mai3dan1: get the bill
总是 zong3shi3: always 100%
自私 zi4si1: selfish
相信 xiang1xin4: believe

** 9 日 17 月 2024 年
买给他 buy it for him
糟糕 zao1gao1 terrible/oops
很久以前 a long time ago
殖民地 zhi2min2di4: colony
收到 shou1dao4: receive
响尾蛇 xian3wei3she2: rattlesnake
一条蛇 yitiao2 she2 a snake
政府 zheng4fu3: government
没办法 mei2ban4fa3: no way
好办法 hao3bn4fa3: good solution
好主意 hao3 zhu3yi4: good idea
抓 zhua1: catch
抓一条蛇 zhuayitiao2 she2: catch a snake
发现: faxian: discover
现在 xian4zai: now
骗我 pian4wo3: lie to me
习惯 xi2guan4: habit
马路 ma3lu4: road

警车 jing3che1: police car
非法 fei1fa3: illegal
法律 fa3lv4: law
警车 jing3che1: police car

难的 nan2de: difficult
适合 shi4he2: suitable
正 zheng4: just
证书 zheng4shu1: certificated
教堂 jiao4tang2: church
硕士证书
硕士毕业 shuo4shi4 bi4ye4: master degree
专心 zhuan1xin1 concentrate
收集 shou1ji2 : collect
手机 shou3ji1: cell phone


** October 2024
负责任 fu4ze2ren4 responsible
产品 chan3pin3 product
咻鹠所有电子产品 xiu1liu2 suo3you3 ... all electronic products
所有 suo3you3 all
装修 zhuangxiu1
婚姻 hunyin marriage (n)
结婚 jie2hun1 marry (v)
结婚纪念日 jie2hun1 ji4nian4ri4 wedding anniversaries

另外 ling4wai4 in addition
刚才 gang1cai2 just now
本来 ben3lai2 originally
一边 yibian

一条内裤 yi1tiao2 nei4ku4 a pair underwear
一双袜子 yishuang1 wazi a pair of socks
播客 bo4ke4 podcast
计划 ji4hu4 plan
永远 yong3yuan3 forever
文化 wen2hu4 culture
答案 da2'an4 answer
送你 song4 ni3 drop you off
接你 jie1ni3 pick you off
借 jie4 borrow
类似 lei4si4 similar
骂 ma4 scold
骂脏话 ma4zang1hua4 swearing
发生了什么事儿 what happened?
得到了 de2dao4le got it

松一口气 song1 yi1kou3qi4
卡片 kapian card
互相 hu4xiang1 each other/mutual/mutually
不一样的方法 bu4 yi1yang4 de fang1fa3 a different approach/method
方法 fang1fa3 approach

农村 non2cun1 village (rural)
伸手 shenshou3 reach out

*** 提前 ti2qian2 in advance/early
*** 准时 zhun3shi2 on time
*** 迟到 chi2dao4 late
不管 bu4guan2 in spite of
收入 shou1ru4 income
努力 nu3li4 effort
赚钱 zhuan4qian2 make money
紧迫 jin3po4 urgent
通知 tong1zhi1 notification
工作的通知 gong1zuo4 de tongzhi1: work notification
一般 yiban1 generally
通常 tong1chang2: generally
森林 sen1lin2: forest
丛林 cong2lin2: jungle

国立 guo2li4: national/public - state run
公立 gong1li4: public
诊所 zhen3suo3: clinic
健康的部门 jian4kang1: department of health
卫生部门 wei4sheng1 bumen: department of health/hygiene
卫生 wei4sheng1: health/hygiene
移民部门 yi2min2 bu4men2: immigration department
身体 shenti3: body
